# Generated by Django 6.0.5 on 2026-06-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask_detected', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='captures/')),
                ('confidence', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'detection_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
